### PR TITLE
Use different alert query for MySQL and PostgreSQL

### PR DESCRIPTION
**Pull request by teaearlgraycold**
In response to @atomicturtle on this PR: https://github.com/ossec/ossec-hids/pull/770

### CODE REVIEW

**Comment by ddpbsd** [comment]
Anyone use ossec-dbd that wants to test this?

**Comment by atomicturtle** [comment]
Yeah I've got the test environment for this one. I'll get to it shortly

**Comment by atomicturtle** [comment]
I'm not having any success getting this to work with mysql, it keeps defaulting to the postgres case for some reason

**Comment by teaearlgraycold** [comment]
I honestly wouldn't be surprised if that dbtype flag isn't being set correctly. The dbd module doesn't feel very fleshed out.

**Comment by atomicturtle** [comment]
Right now this is a release blocking issue & we may need to revert the postgres commit

**Comment by atomicturtle** [comment]
Im going to close this one out, I re-implemented this PR in #824 with the break; fix

Thanks again for the PR!

**Pull request closed without merging**
