### PR TITLE
Ossec server and agent systemd units for #594

### PR DESCRIPTION
**Pull request by dsvetlov**
Hello!

Here is units for systemd. It is for issue #594
If it'll be OK, I will make patch for install.sh too.

This units can completly replace ossec-control script.

### CODE REVIEW

**Comment by awiddersheim** [comment]
Your RPM changes snuck into this it looks like. Can you remove those to keep this concise?

**Comment by dsvetlov** [comment]
@awiddersheim,  you mean merge all commits in one?

**Comment by dsvetlov** [comment]
@awiddersheim , ok. I understand. Will do tomorrow.

**Comment by awiddersheim** [comment]
No. You already have a pull request open to address the RPM spec file changes. This pull request is about systemd unit files so to have the RPM spec changes in this pull request is confusing.

**Comment by awiddersheim** [comment]
@dsvetlov great thanks.

**Comment by dsvetlov** [comment]
@awiddersheim, sorry. I'm not very experienced with git, and seems I make some mistakes while making  pull request. I will create new one clearly.

**Pull request closed without merging**
