### PR TITLE
Update cJSON to 1.5.9

### PR DESCRIPTION
**Pull request by ddpbsd**
Totally untested as of yet. Working on it though.
Any tests/results would be appreciated!

### CODE REVIEW

**Comment by marcRBD** [comment]
hello
mv cJSON-1.5.9 ossec-hids-2.9.2/src/external/cJSON/


the compilation 
``make TARGET=agent build
    CC external/cJSON/cJSON.o
    LINK libcJSON.a
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
    RANLIB libcJSON.a
cd external/zlib-1.2.8/ && ./configure && make libz.a
Checking for gcc...
Checking for shared library support...
Building shared library libz.so.1.2.8 with gcc.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.
make[1] : on entre dans le répertoire « /root/ossec-hids-2.9.2/src/external/zlib-1.2.8 »
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o adler32.o adler32.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o crc32.o crc32.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o deflate.o deflate.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o infback.o infback.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o inffast.o inffast.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o inflate.o inflate.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o inftrees.o inftrees.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o trees.o trees.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o zutil.o zutil.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o compress.o compress.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o uncompr.o uncompr.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o gzclose.o gzclose.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o gzlib.o gzlib.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o gzread.o gzread.c
gcc -O3  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o gzwrite.o gzwrite.c
ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o
make[1] : on quitte le répertoire « /root/ossec-hids-2.9.2/src/external/zlib-1.2.8 »
cd external/lua/ && make posix
make[1] : on entre dans le répertoire « /root/ossec-hids-2.9.2/src/external/lua-5.2.3 »
cd src && make posix
make[2] : on entre dans le répertoire « /root/ossec-hids-2.9.2/src/external/lua-5.2.3/src »
make all SYSCFLAGS="-DLUA_USE_POSIX"
make[3] : on entre dans le répertoire « /root/ossec-hids-2.9.2/src/external/lua-5.2.3/src »
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lapi.o lapi.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lcode.o lcode.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lctype.o lctype.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o ldebug.o ldebug.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o ldo.o ldo.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o ldump.o ldump.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lfunc.o lfunc.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lgc.o lgc.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o llex.o llex.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lmem.o lmem.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lobject.o lobject.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lopcodes.o lopcodes.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lparser.o lparser.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lstate.o lstate.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lstring.o lstring.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o ltable.o ltable.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o ltm.o ltm.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lundump.o lundump.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lvm.o lvm.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lzio.o lzio.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lauxlib.o lauxlib.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lbaselib.o lbaselib.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lbitlib.o lbitlib.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lcorolib.o lcorolib.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o ldblib.o ldblib.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o liolib.o liolib.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lmathlib.o lmathlib.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o loslib.o loslib.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lstrlib.o lstrlib.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o ltablib.o ltablib.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o loadlib.o loadlib.c
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o linit.o linit.c
ar rcu liblua.a lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o lauxlib.o lbaselib.o lbitlib.o lcorolib.o ldblib.o liolib.o lmathlib.o loslib.o lstrlib.o ltablib.o loadlib.o linit.o
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
ranlib liblua.a
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o lua.o lua.c
cc -o ossec-lua   lua.o liblua.a -lm
cc -O2 -Wall -DLUA_COMPAT_ALL -DPREFIX=\"/var/ossec\" -DLUA_USE_POSIX    -c -o luac.o luac.c
cc -o ossec-luac   luac.o liblua.a -lm
make[3] : on quitte le répertoire « /root/ossec-hids-2.9.2/src/external/lua-5.2.3/src »
make[2] : on quitte le répertoire « /root/ossec-hids-2.9.2/src/external/lua-5.2.3/src »
make[1] : on quitte le répertoire « /root/ossec-hids-2.9.2/src/external/lua-5.2.3 »
    CC client-agent/sendmsg.o
    CC client-agent/intcheck_op.o
    CC client-agent/agentd.o
    CC client-agent/config.o
    CC client-agent/event-forward.o
    CC client-agent/receiver.o
    CC client-agent/main.o
    CC client-agent/receiver-win.o
    CC client-agent/start_agent.o
    CC client-agent/notify.o
    CC os_crypto/blowfish/bf_op.o
    CC os_crypto/blowfish/bf_skey.o
    CC os_crypto/blowfish/bf_enc.o
    CC os_crypto/md5/md5.o
    CC os_crypto/md5/md5_op.o
    CC os_crypto/sha1/sha1_op.o
    CC os_zlib/os_zlib.o
    LINK os_zlib.a
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
    RANLIB os_zlib.a
    CC os_crypto/shared/keys.o
    CC os_crypto/shared/msgs.o
    CC os_crypto/md5_sha1/md5_sha1_op.o
    LINK os_crypto.a
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
    RANLIB os_crypto.a
    CC config/localfile-config.o
    CC config/rootcheck-config.o
    CC config/agentlessd-config.o
    CC config/active-response.o
    CC config/remote-config.o
    CC config/reports-config.o
    CC config/config.o
    CC config/email-alerts-config.o
    CC config/global-config.o
    CC config/rules-config.o
    CC config/dbd-config.o
    CC config/syscheck-config.o
    CC config/alerts-config.o
    CC config/csyslogd-config.o
    CC config/client-config.o
    LINK config.a
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
    RANLIB config.a
    CC shared/file-queue.o
    CC shared/read-alert.o
    CC shared/fs_op.o
    CC shared/store_op.o
    CC shared/mem_op.o
    CC shared/regex_op.o
    CC shared/file_op.o
    CC shared/report_op.o
    CC shared/sig_op.o
    CC shared/wait_op.o
    CC shared/help.o
    CC shared/list_op.o
    CC shared/mq_op.o
    CC shared/privsep_op.o
    CC shared/dirtree_op.o
    CC shared/custom_output_search_replace.o
    CC shared/debug_op.o
    CC shared/math_op.o
    CC shared/rules_op.o
    CC shared/string_op.o
    CC shared/read-agents.o
    CC shared/pthreads_op.o
    CC shared/hash_op.o
    CC shared/validate_op.o
shared/validate_op.c: In function ‘sacmp’:
shared/validate_op.c:396:31: warning: left shift of negative value [-Wshift-negative-value]
         modbits = ((char) ~0) << (8 - ip_div.rem);
                               ^~
    CC shared/randombytes.o
    CC shared/agent_op.o
    LINK shared.a
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
    RANLIB shared.a
    CC os_net/os_net.o
    LINK os_net.a
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
    RANLIB os_net.a
    CC os_regex/os_regex_match.o
    CC os_regex/os_regex.o
    CC os_regex/os_regex_str.o
os_regex/os_regex_str.c: In function ‘OS_StrIsNum’:
os_regex/os_regex_str.c:21:8: warning: nonnull argument ‘str’ compared to NULL [-Wnonnull-compare]
     if (str == NULL) {
        ^
    CC os_regex/os_match.o
    CC os_regex/os_regex_compile.o
    CC os_regex/os_regex_startswith.o
    CC os_regex/os_regex_free_pattern.o
    CC os_regex/os_match_compile.o
    CC os_regex/os_regex_strbreak.o
    CC os_regex/os_match_free_pattern.o
    CC os_regex/os_regex_maps.o
    CC os_regex/os_regex_execute.o
    CC os_regex/os_regex_free_substrings.o
    CC os_regex/os_match_execute.o
    LINK os_regex.a
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
    RANLIB os_regex.a
    CC os_xml/os_xml_variables.o
    CC os_xml/os_xml.o
    CC os_xml/os_xml_access.o
    CC os_xml/os_xml_node_access.o
    CC os_xml/os_xml_writer.o
    LINK os_xml.a
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
    RANLIB os_xml.a
    CC ossec-agentd
    CC addagent/validate.o
    CC os_auth/main-client.o
    CC os_auth/ssl.o
    CC os_auth/check_cert.o
    CC agent-auth
    CC logcollector/read_ossecalert.o
    CC logcollector/read_command.o
    CC logcollector/config.o
    CC logcollector/read_djb_multilog.o
    CC logcollector/read_postgresql_log.o
    CC logcollector/main.o
    CC logcollector/read_mssql_log.o
    CC logcollector/read_win_el.o
    CC logcollector/read_win_event_channel.o
    CC logcollector/read_syslog.o
    CC logcollector/read_nmapg.o
    CC logcollector/logcollector.o
    CC logcollector/read_mysql_log.o
    CC logcollector/read_multiline.o
    CC logcollector/read_fullcommand.o
    CC logcollector/read_snortfull.o
    CC ossec-logcollector
    CC syscheckd/run_realtime.o
    CC syscheckd/config.o
    CC syscheckd/create_db.o
syscheckd/create_db.c: In function ‘read_dir’:
syscheckd/create_db.c:264:8: warning: nonnull argument ‘dir_name’ compared to NULL [-Wnonnull-compare]
     if ((dir_name == NULL) || ((dir_size = strlen(dir_name)) > PATH_MAX)) {
        ^
    CC syscheckd/syscheck.o
    CC syscheckd/seechanges.o
    CC syscheckd/run_check.o
    CC syscheckd/win-registry.o
    CC rootcheck/unix-process.o
    CC rootcheck/config.o
    CC rootcheck/check_rc_files.o
    CC rootcheck/check_rc_ports.o
    CC rootcheck/common_rcl.o
    CC rootcheck/win-process.o
    CC rootcheck/common.o
    CC rootcheck/rootcheck.o
    CC rootcheck/check_rc_if.o
    CC rootcheck/check_rc_sys.o
    CC rootcheck/check_open_ports.o
    CC rootcheck/os_string.o
    CC rootcheck/win-common.o
    CC rootcheck/check_rc_readproc.o
    CC rootcheck/check_rc_dev.o
    CC rootcheck/run_rk_check.o
    CC rootcheck/check_rc_policy.o
    CC rootcheck/check_rc_pids.o
    CC rootcheck/check_rc_trojans.o
    LINK rootcheck.a
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
    RANLIB rootcheck.a
    CC ossec-syscheckd
    CC os_execd/exec.o
    CC os_execd/config.o
    CC os_execd/execd.o
    CC os_execd/win_execd.o
    CC ossec-execd
    CC addagent/read_from_user.o
    CC addagent/b64.o
    CC addagent/main.o
    CC addagent/manage_keys.o
    CC addagent/manage_agents.o
    CC manage_agents
make settings
make[1] : on entre dans le répertoire « /root/ossec-hids-2.9.2/src »

General settings:
    TARGET:           agent
    V:
    DEBUG:
    DEBUGAD
    PREFIX:           /var/ossec
    MAXAGENTS:        2048
    DATABASE:
    ONEWAY:           no
    CLEANFULL:        no
User settings:
    OSSEC_GROUP:      ossec
    OSSEC_USER:       ossec
    OSSEC_USER_MAIL:  ossecm
    OSSEC_USER_REM:   ossecr
Lua settings:
    LUA_PLAT:         posix
USE settings:
    USE_ZEROMQ:       no
    USE_GEOIP:        no
    USE_PRELUDE:      no
    USE_OPENSSL:      auto
    USE_PICVIZ:       yes
    USE_INOTIFY:      no
Mysql settings:
    includes:
    libs:
Pgsql settings:
    includes:
    libs:
Defines:
    -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR="/var/ossec" -DUSER="ossec" -DREMUSER="ossecr" -DGROUPGLOBAL="ossec" -DMAILUSER="ossecm" -DLinux -DINOTIFY_ENABLED -DPICVIZ_OUTPUT_ENABLED -DCLIENT
Compiler:
    CFLAGS           -O2 -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR="/var/ossec" -DUSER="ossec" -DREMUSER="ossecr" -DGROUPGLOBAL="ossec" -DMAILUSER="ossecm" -DLinux -DINOTIFY_ENABLED -DPICVIZ_OUTPUT_ENABLED -DCLIENT -Wall -Wextra -I./ -I./headers/
    LDFLAGS          -lm -lpthread
    CC              cc
    MAKE            make
make[1] : on quitte le répertoire « /root/ossec-hids-2.9.2/src »

Done building agent

``

i will give a few test soon

**Comment by marcRBD** [comment]
I don't think it change most things, as we have the same error outside cjson perimeter between the two versions of cjson in compilation 1.5.8 / 1.5.9

**Comment by marcRBD** [comment]
Thanks (hope it is not some Null_Dereference ;))

**Comment by ddpbsd** [comment]
`shared/validate_op.c:396:31: warning: left shift of negative value [-Wshift-negative-value]`
I'll have to look into this one. I've never seen it before.

`os_regex/os_regex_str.c:21:8: warning: nonnull argument ‘str’ compared to NULL [-Wnonnull-compare]`
str shouldn't be null, but we check it anyway. I don't want some strange change to make null a possibility, and not have this check in place just in case. I don't think (and hopefully if I'm wrong someone will educate me) this extra check is a problem.

**Comment by marcRBD** [comment]
Let me know when you need some test for this bug or another, maybe sometimes i can help.
as i have a strong infrastucture for testing.
Best regards and thanks for the work

**Pull request merged**
