### PR TITLE
Zlib update

### PR DESCRIPTION
**Pull request by ddpbsd**
Update zlib to 1.2.11. Fixes several CVEs as documented in issue #1186 
Includes the cJSON update, so that should be applied first.
Both need more testing.

### CODE REVIEW

**Comment by nbuuck** [comment]
I worked to test the zlib commits (590d9cb, 70d1f85, af9a257) but was testing with the Windows agent (2.9.0). The agent could connect on UDP/1514 but ossec-agent never successfully exchanged a message with the server. Will need to troubleshoot further.

**Comment by ddpbsd** [comment]
I guess it's possible you'll have to compile the Windows agent with the new version of zlib.

**Comment by nbuuck** [comment]
That, or for a faster initial test, deploy a *nix VM as a new agent. Either way, I'll follow up on this effort.

**Comment by nbuuck** [comment]
The patch for 70d1f85 has a few warnings when applying with `git apply`, just an FYI, @ddpbsd:

> [root@REDACTED REDACTED]# git apply --directory /home/REDACTED/ossec-hids-master/ 70d1f85b40ca1bd7cd0c7832c29a9c2e63cb10e8.patch
> 70d1f85b40ca1bd7cd0c7832c29a9c2e63cb10e8.patch:7848: trailing whitespace.
> #else
> 70d1f85b40ca1bd7cd0c7832c29a9c2e63cb10e8.patch:8044: trailing whitespace.
> 
> 70d1f85b40ca1bd7cd0c7832c29a9c2e63cb10e8.patch:8046: trailing whitespace.
>                    incremented rdx by 0x108 (each loop iteration add 16*4 = 0x40
> 70d1f85b40ca1bd7cd0c7832c29a9c2e63cb10e8.patch:8052: trailing whitespace.
> 
> 70d1f85b40ca1bd7cd0c7832c29a9c2e63cb10e8.patch:8057: trailing whitespace.
> 
> warning: squelched 16883 whitespace errors
> warning: 16888 lines add whitespace errors.

**Comment by nbuuck** [comment]
Same test mentioned [here](https://github.com/ossec/ossec-hids/pull/1198#issuecomment-317014634) failed with a rebuilt agent from master with patches 590d9cb, 70d1f85, af9a257 running the same CentOS build as the server (CentOS Linux release 7.3.1611 (Core)). Going to review a packet capture and look at debug options for the server process.

**Comment by ddpbsd** [comment]
I'm not cleaning up the zlib codebase. I want to keep changes to a minimum.

**Comment by nbuuck** [comment]
@ddpbsd Lacking much experience here, should I proceed trying to troubleshoot zlib-1.2.11 or should we revert to zlib-1.2.8?

**Comment by nbuuck** [comment]
My remoted problems were due to a bad iptables ALLOW. Agent and server built with zlib-1.2.11 can communicate, though unmerging `merged.mg` failed on the agent for all .txt files included. `ar.conf` was successfully extracted.

**Comment by ddpbsd** [comment]
I saw the same issue, but I didn't use the RPMs. It seems to be working now.
I added the fopen error into the error message OSSEC provides for a bit more verbosity.

**Comment by ddpbsd** [comment]
If I'm looking at the right spot in the `.spec` file, I think `770` should work, but I'll go ahead and chown them to ossec instead.
```
/var/ossec/etc/shared/win_malware_rcl.txt
%attr(770, root, ossec) /var/ossec/etc/shared/win_malware_rcl.txt
/var/ossec/etc/shared/win_applications_rcl.txt
%attr(770, root, ossec) /var/ossec/etc/shared/win_applications_rcl.txt
/var/ossec/etc/shared/win_audit_rcl.txt
%attr(770, root, ossec) /var/ossec/etc/shared/win_audit_rcl.txt
/var/ossec/etc/shared/rootkit_files.txt
%attr(770, root, ossec) /var/ossec/etc/shared/rootkit_files.txt
/var/ossec/etc/shared/rootkit_trojans.txt
%attr(770, root, ossec) /var/ossec/etc/shared/rootkit_trojans.txt
```

**Pull request merged**
