### PR TITLE
Support arm64 packaging

### LINKED ISSUE #1073: Packages for ARM machines
I want to use a Raspberry Pi 3 as manager to collect logs and do all process on my small home network but I would need ARM-compatible binaries. My idea is support the two main ARM architectures, arm64 and armhf on DEB and RPM repositories. I know I could log remotely and compile myself (I just need a C compiler!) but I can do much automation in that way. I prefer add a repository and just let update itself.

### PR DESCRIPTION
**Pull request by nurse**
Though this PR is some rough points, this successfully create a deb package for arm64.
I want to merge this PR but I noticed current `generate_ossec.sh` doesn't work well now.
So before I blush up this I ask you how to improve this PR.

fix #1073

```
# setup gnupg key in ~/.gnupg
# write passphrase of gnupg key in ~/.gnupg/passphrase
# Update `signing_key` in contrib/debian-packages/generate_ossec_xenial_arm64.sh
docker build -t ossec-hids-agent .
docker run --rm -it --privileged -v$HOME/.gnupg:/root/.gnupg ossec-hids-agent /bin/bash
/home/ubuntu/ossec-hids/contrib/debian-packages/generate_ossec_xenial_arm64.sh -a
# results are in /var/cache/pbuilder/xenial-arm64/result/
```

### CODE REVIEW

**Comment by atomicturtle** [comment]
This is fantastic, Id love to get packages for this added into the repo. Let me know if you want a slack invite (slack@ossec.net) if you want to coordinate!

**Comment by atomicturtle** [comment]
I have some changes that will address issues #1810 and #1807 that Id like to do after your commit is in so I can capture it on both. Let us know when you're done with your update!

**Comment by nurse** [comment]
Thanks! I mailed to request an invitation.

Also I updated my PR to add Dockerfile to provide more reproducible example.

**Comment by nurse** [comment]
@atomicturtle Hi,
I sent a mail but no response now. Could you check it?
thanks,

**Comment by zfouts** [comment]
Hi @atomicturtle - hope you're doing well :) I work with @nurse and I was curious if you had a chance to move forward with this. It's not currently a blocker as we can host the packages ourselves to move forward, but we're hoping to help others out in the community :) Thanks for your time!

**Comment by atomicturtle** [comment]
Sure, this is still marked as a Draft pull request on your side so I cant merge it from here.  @nurse  would need to change that setting, and then we can push this into main. I dont have any other changes otherwise (we already added the arm64 packages to the repo)

**Comment by nurse** [comment]
It says "CI build failed" but actually on travis it successfully ran.
https://travis-ci.org/github/ossec/ossec-hids/builds/698913107

**Pull request merged**
