### PR TITLE
sshd rule addition

### PR DESCRIPTION
**Pull request by ddpbsd**
Adjust the rules to handle a log message provided by @colinmollenhour in PR #786

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Thanks, Dan!

**Comment by ddpbsd** [comment]
My master branch (which I shouldn't have submitted this from in the first place) has now picked up some corrections to the README.md file. If necessary, I can pull those out and submit them separately.

**Comment by colinmollenhour** [comment]
@atomicturtle it seems your merge was faulty and has clobbered the commits added in this PR. Specifically 32e52c9 and 7133703.

Just FYI, I think using git rebase to keep only what you needed instead of making new commits to remove mistakes would have prevented the mixup.

**Comment by ddpbsd** [comment]
I think this was my fault. I'll resubmit a new PR shortly.

**Comment by ddpbsd** [comment]
Ok, PR #826 should fix it. That'll teach me to commit to my own master.

**Comment by colinmollenhour** [comment]
Thanks again!

**Pull request merged**
