### PR TITLE
Fix windows event channel

### PR DESCRIPTION
**Pull request by awiddersheim**
Quite a few changes/fixes/updates to the Windows event channel code. Many changes were done to help address issues in https://github.com/ossec/ossec-hids/issues/224. Some testing was done by myself and @defensivedepth but more testing would certainly be appreciated. Need people who use Windows and event channel.

Tried to make the output from the `eventlog` format and the `eventchannel` format as similar as possible. Added a lot of error checking. Fixed issues where not all log messages were able to be displayed. Moved to using temporary files and atomic moves to update bookmarks.

### CODE REVIEW

**Comment by defensivedepth** [comment]
Just an update on this... I am noticing a much higher than average ossec client memory usage on the 2008 R2 servers using this build... A couple of them are 500mb up to 800mb, with only an up-time of 2 days...

**Comment by awiddersheim** [comment]
Hrm, is the memory rising or does it stay at that level? What are "normal" levels when it comes to OSSEC on Windows? 

Sounds like a memory leak. Question is, is the leak in the eventchannel code or somewhere else. The build you are using has not only my changes but quite a few others that MAY be causing issues. Any errors in the OSSEC log? If you disable eventchannel and restart the agent does the memory issue persist?

**Comment by defensivedepth** [comment]
After looking into this further, It appears to gradually increase after a reboot until all memory is consumed on the box...  

Normal levels that I have typically observed is under 10mb...  

No errors in the OSSEC log.

I will disable event channel, restart the agent and get back to you on if the issue persists...

**Comment by awiddersheim** [comment]
Definitely seems like a memory leak. I see a few issues with the event channel code that might fix the issue but might take me a bit before I get enough free time to work on it. Let me know how your testing goes with disabling event channel.

**Comment by defensivedepth** [comment]
After disabling the eventchannel logs and restarting the agent, memory usage sat at under 10mb for the next 5 hours. 

Once I enabled the eventchannel logs and restarted the agent, I saw an instant CPU & memory spike (which is to be somewhat expected, as it shipped off the 50k events that were generated and not sent to the OSSEC server during those 5 hours).. During this time when the new events were being processed, the memory usage of the agent went from <10mb to 127mb, and then the memory increase became much slower, correlating to when the agent stopped processing the backlog.  

During the next hour, memory usage continued to increase, but more slowly... Currently at 155mb and increasing.

Based on this testing, I would agree that the leak appears to be related with the eventchannel code. 

No worries on the timing... If I have to have this functionality right now, I can just set the agent to restart hourly...

**Comment by awiddersheim** [comment]
Great info and testing notes. Thanks for testing and helping to narrow this down.

**Comment by defensivedepth** [comment]
Let me know if I can do any more testing, etc

**Comment by awiddersheim** [comment]
Found that this buffer never has `free()` called.

https://github.com/ossec/ossec-hids/blob/master/src/logcollector/read_win_event_channel.c#L572

This is probably the biggest source of memory leakage that I created.

@jrossi also pointed out several spots where I should be doing an `EvtClose()` on event handles. Should have something shortly that will hopefully fix things.

**Comment by awiddersheim** [comment]
Most of the memory leaks were fixed in https://github.com/ossec/ossec-hids/pull/496. Turns out I didn't introduce the memory leaks after all. Most were already there I just didn't see them.

**Pull request merged**
