### PR TITLE
remove unknown code

### PR DESCRIPTION
**Pull request by cgzones**

### CODE REVIEW

**Comment by jrossi** [comment]
wow - @dcid normally did not add weird things like this into code.  I wonder what this was for.......

**Comment by cgzones** [comment]
i already asked for the purpose of this code in #327, but no answer was given, so ...

**Comment by ddpbsd** [comment]
@cgzones Did you ask dcid?

**Comment by jrossi** [comment]
@ddpbsd i think i did as one point - will need to check into email :) don't think he remembered.

**Pull request merged**
