### PR TITLE
Fix host deny

### PR DESCRIPTION
**Pull request by ddpbsd**

### CODE REVIEW

**Comment by RealRancor** [comment]
Hi,

any chances to get this into one of the 2.8.x releases? Thats an really annoying bug and i really wonder why this wasn't released in one of the last few maintenance releases of 2.8.x

**Comment by ddpbsd** [comment]
There aren't currently any plans for another 2.8.x release. I am hoping to focus on a 2.9 release though.

**Comment by RealRancor** [comment]
Hey, thanks for your reply. If there are no 2.8.x releases planned then it should be fine as 2.9 has included this fix.

Was just annoying that this fix needs to be applied after each 2.8.x release.

**Comment by ddpbsd** [comment]
@RealRancor I wish someone had mentioned it in the long time 2.8.3 was being prepped. I would have gladly included it.

**Comment by RealRancor** [comment]
@ddpbsd Sorry, had completely forgotten to ping here to include it in one of the 2.8.x releases. :-/

**Pull request merged**
