### PR TITLE
Possible fix for Issue #442: logcollector stops reading alerts.log

### PR DESCRIPTION
**Pull request by ddpbsd**
I think this needs a decent amount of testing before it's included (unless someone works out the logic and I happen to be correct), but this seems to have fixed the issue of logcollector ignoring alerts.log

r usually does not equal 0, and this does not appear to be a parsingerror. logff[i].ign was being ++'d at that point every loop through, and is later compared to open_file_attempts. If you raise ign every time it's going to quickly be higher than open_file_attempts.

### CODE REVIEW

**Comment by jrossi** [comment]
#442

**Comment by jrossi** [comment]
Anyone else testing this? @ossec

**Comment by jrossi** [comment]
I have not be able to test this.  Cannot someone else from @ossec look into this one?

**Comment by ddpbsd** [comment]
There's a report of logs not being sent to the central manager after midnight when using this patch. I haven't confirmed if logs are sent prior to midnight though.

**Comment by ddpbsd** [comment]
My crappy test setup is having a bunch of issues I'm going to blame on this. Closing for now, and will open a new pull request if I come up with anything.

**Pull request closed without merging**
