### PR TITLE
Output alerts.json, newline delimited json, beside the alerts.log file.

### PR DESCRIPTION
**Pull request by jondb**
Install as normal

    ./install.sh

Enable jsonout in global section of ossec.conf:

    <jsonout_output>yes</jsonout_output>

View the current output file at ossec/logs/alerts/alerts.json

### CODE REVIEW

**Comment by jrossi** [comment]
I read this patch once and looks great.  Should accept this soon once I get to reading again and running the code some.

**Comment by jrossi** [comment]
@ddpbsd pointed out that the makefile changes are completely not needed as all dependencies are already part of ossec.  To make this easy can you always built this support in?

**Comment by jondb** [comment]
I would actually prefer that. I'll update.

On Wed, Feb 18, 2015 at 8:51 AM, Jeremy Rossi <notifications@github.com>
wrote:

> @ddpbsd <https://github.com/ddpbsd> pointed out that the makefile changes
> are completely not needed as all dependencies are already part of ossec. To
> make this easy can you always built this support in?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ossec/ossec-hids/pull/551#issuecomment-74899793>.
>



-- 
jondebonis@gmail.com

**Comment by jondb** [comment]
@jrossi, Makefile and ifdef changes removed.

**Comment by jrossi** [comment]
Thank you for this patch.  If you could submit a pull request to ossec/ossec-docs with the details of this new feature that would be great.

**Pull request merged**
