### PR TITLE
Remove prelude support.

### PR DESCRIPTION
**Pull request by ddpbsd**
I don't want to maintain it. You probably don't want to maintain it. Does prelude still exist?

---
This change is [Reviewable](https://reviewable.io/reviews/ossec/ossec-hids/1071)

### CODE REVIEW

**Comment by marcRBD** [comment]
For information:
Yes still exist, and they encourage ossec as main HIDS source :/
you must have your good reasons, i'm bot a big fan of it

**Comment by ddpbsd** [comment]
I think prelude (and similar technologies) would be better supported by external daemons. Something similar to how `ossec-maild` works. Putting the extra logic and complexity in an already complex process feels inefficient.

**Comment by marcRBD** [comment]
Sure !

**Comment by ToToL** [comment]
Hello, I'm the technical manager of Prelude. Too bad you remove this, many of our client use it.

I will works on the ossec-prelude but other IDS like Suricata keep prelude notifications inside.

**Comment by ddpbsd** [comment]
@ToToL It hasn't been removed. This is basically just a proposal at this point.

My thoughts on this are that analysisd is insanely complex (to me). Removing "extras" that aren't generally used helps remove bits of complexity. 

I would much rather move the prelude support to an external daemon (like maild, csyslogd, etc) to make working on/with analysisd easier. Of course, I don't use prelude, so writing that daemon isn't something I had planned on working on.

But since there is at least some support for the prelude support, maybe that's something I need to work on before removing this. I won't merge this right now, but no promises in the future.

**Comment by ToToL** [comment]
I started to do the move : https://github.com/ToToL/ossec-hids/commit/master

But to generate the IDMEF alert, I need information (like lf->generated_rule) decoded by analysisd. I can't find out the right way to get this, can you help me ? Read_FileMon only get me alert_data

**Comment by ddpbsd** [comment]
What information do you need from there? I see mostly level, comment, and sigid. I'm not sure about the CVE stuff. Maybe that's something that can be added to the alerts.json output.

**Comment by ToToL** [comment]
Fields that analysisd provide through it Eventinfo struct but I don't have in alert_data :
* generated_rule->comment
* generated_rule->level
* action
* generated_rule->cve
* generated_rule->sigid
* generated_rule->info_details

**Comment by ToToL** [comment]
* generated_rule->info_details->type
* generated_rule->info_details->data
* generated_rule->group
* srcport
* srcuser
* program_name
* hostname
* dstport
* full_log

**Comment by ToToL** [comment]
* owner_before
* perm_before

Sorry for the three message,

So, for these fields, analysisd do OSSECAlert_Decoder to get them. How can I get these from alert_data ?

Do I need to reeimplement OSSECAlert_Decoder or include analysisd code into ossec-prelude ?

Thanks

**Comment by ddpbsd** [comment]
I haven't checked, but I think a lot of these line up.

```
typedef struct _alert_data {
    unsigned int rule;  // generated_rule->sigid
    unsigned int level; // generated_rule ->level
    char *alertid;
    char *date;
    char *location;    // hostname?
    char *comment;  // generated_rule->comment
    char *group;  // group
    char *srcip;
    int srcport;    // srcport
    char *dstip;
    int dstport;    // dstport
    char *user;    // srcuser?
    char *filename;
    char *old_md5;
    char *new_md5;
    char *old_sha1;
    char *new_sha1;
    char **log;     // fulle_log?
    char *srcgeoip;
    char *dstgeoip;
    /* "9/19/2016 - Sivakumar Nellurandi - parsing additions" */
    char *file_size;
    char *owner_chg;
    char *group_chg;
    char *perm_chg;
    /* "9/19/2016 - Sivakumar Nellurandi - parsing additions" */
} alert_data;
```

You can look at how maild gets the information it gets for these. Or look into parsing the alerts.json log file.  The json output would be easier to extend if we needed to add more information to it.

**Comment by ToToL** [comment]
Yes I saw that but there are missing values :
generated_rule->info_details
generated_rule->cve
action
program_name

I will look if I find them.
Else, do you know someone that can help me on this ?

**Comment by ddpbsd** [comment]
Looks like prelude is alive? https://twitter.com/PreludeSIEM/status/908720405216681984
Closing this, will revisit later.

**Comment by ToToL** [comment]
Prelude IS alive :). We released the 4.0 version in july and we are migrating all Linux distributions one by one.

I do not had time this past summer to work on this but for what I looked for, I can't find how to get all information like actuals implementation.

Tweet updated : https://twitter.com/PreludeSIEM/status/908732372044144640

**Comment by ddpbsd** [comment]
This is still something I want to move from analysisd to its own daemon, but from what you posted, I think more work needs to be done. And I don't have time for it at the moment.

**Pull request closed without merging**
