### PR TITLE
Patch8

### PR DESCRIPTION
**Pull request by hcw2016**
Several changes were made to support TCP for secure connections. Changes came from the patch files as well as Wazuh.

---
This change is [Reviewable](https://reviewable.io/reviews/ossec/ossec-hids/1162)

### CODE REVIEW

**Comment by aquerubin** [comment]
You've reintroduced a number of IPv4 dependencies into the code.  Can you redo in a IP version agnostic way?

Tony

**Comment by hcw2016** [comment]
Mr. Querubin,

I am unsure of what you are asking. Did I do something wrong with the code?
I noticed that it supported IPV4 and not IPV6. I just want to make sure I
did not mess something up.

Thanks,

Hayden Cody Woods

**Comment by aquerubin** [comment]
That's exactly the point.  OSSEC supports IPv6 and IPv4.  In several places your patches re-introduce code that only supports IPv4.

Tony

**Comment by atomicturtle** [comment]
I dont think we ever merged in that IPv6 PR that added it. When I look at OS_ConnectTCP it was only ipv4 in master:

int OS_ConnectTCP(char *_port, const char *_ip)

I know I saw a change to that for ipv6, but I dont remember where it was

**Comment by aquerubin** [comment]
Actually, if you look back at the history, a lot of the functions had a third argument to specify whether to do IPv4 or IPv6.  And they passed IP addresses and ports as 32-bit ints.  However, the code to actually handle IPv6 was missing.  The big IPv6 PR pulled all of that kludginess out and actually simplified and reduced the code base in many places.

Tony

**Comment by atomicturtle** [comment]
A ha! I knew I wasnt crazy for remembering those had 3 args.

**Pull request merged**
