### PR TITLE
Sysmon EventID#1 Decoder & Rules

### PR DESCRIPTION
**Pull request by defensivedepth**
Adds decoder for [Sysmon] (https://technet.microsoft.com/en-us/sysinternals/dn798348) Event ID 1 logs as well as a ruleset to detect Windows Process Anomalies.

See [this topic] (https://groups.google.com/forum/#!topic/ossec-list/clj2j_8QjEc) for more info.

### CODE REVIEW

**Comment by awiddersheim** [comment]
Hmm... the Travis-CI tests failed but we've been having some weird issues recently with the so I'm not sure if it is Travis or the tests.

**Comment by ChristianBeer** [comment]
The test fails because Josh added a new rules file. This needs to be added to some configuration files. I think @ddpbsd investigated this not long ago with some other contributions.

**Comment by defensivedepth** [comment]
Let me know if I need to tweak anything...

**Comment by ddpbsd** [comment]
@defensivedepth I think you do. Try adding sysmon_rules.xml to etc/ossec-server.conf, etc/templates/config/rules.template, etc/ossec.conf, and etc/ossec-local.conf.

**Comment by defensivedepth** [comment]
@ddpbsd Done.

**Comment by ddpbsd** [comment]
Thanks, this has been merged

**Comment by awiddersheim** [comment]
Awesome addition. Thanks @ddpbsd  and @defensivedepth.

**Comment by defensivedepth** [comment]
Fantastic!

**Pull request merged**
