### PR TITLE
V2.8.2

### PR DESCRIPTION
**Pull request by aremai**
Would it be possible to replace the little outdated blowfish cipher with e.g threefish or AES?
If not, why?
Because even samhain uses 192-bit AES....

### CODE REVIEW

**Comment by mstarks01** [comment]
Is there a weakness in Blowfish?

**Comment by awiddersheim** [comment]
I'm confused. Is this a pull request or an issue?

**Comment by aremai** [comment]
sorry for causing confusion. it's a pull/feature request actually.
i'm not aware that there's a weakness in blowfish, but i've recently read that bruce schneier himself recommends using twofish.
https://www.computerworld.com.au/article/46254/bruce_almighty_schneier_preaches_security_linux_faithful/?pp=3

and i was wondering if there was a specific reason for using blowfish.
again sorry for causing confusion!

**Comment by awiddersheim** [comment]
If this is a feature request or issue please create it as such. Making this a pull request makes things very confusing.

**Pull request closed without merging**
