### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by wcc526**
fix bug,append will duplicate the /etc/init.d/ossec file

### CODE REVIEW

**Comment by ddpbsd** [comment]
The `>>` appends to the file. A single `>` over writes the file.
Is that what we want? (I don't know anything about the RPM stuff, so maybe this is what is desired?)

**Comment by wcc526** [comment]
https://stackoverflow.com/questions/48505456/creating-init-script-from-shell-script

**Comment by ddpbsd** [comment]
I understand what the shell code itself does, but I don't know if that's what should happen in the RPM side of things.
Plus, the spec file is for ossec 1.3. I doubt it's relevant to anything anymore.

**Comment by wcc526** [comment]
>> append file, it will cause the duplicate content of /etc/init.d/ossec if the ossec reinstall

**Pull request merged**
