### PR TITLE
Add mysql rootchecks

### PR DESCRIPTION
**Pull request by Bob-Andrews**
New mysql rootcheck-files.

### CODE REVIEW

**Comment by Avamander** [comment]
If someone merges this, please squash this with a good commit message.

**Comment by atomicturtle** [comment]
This is a good commit message.

**Comment by Avamander** [comment]
"Add files via upload" is not a good commit message, it's absolutely useless.

**Comment by ddpbsd** [comment]
The commit message he was commenting on was `Add mysql rootchecks`

**Pull request merged**
