### PR TITLE
Updated IPv4-dependent regexp in ownCloud decoders.

### PR DESCRIPTION
**Pull request by aquerubin**
Updated IPv4-dependent regexp in ownCloud decoders.

### CODE REVIEW

**Comment by iasdeoupxe** [comment]
@aquerubin @ddpbsd Are you sure that this is a correct change for this? If you check the examples in the decoder below you can see that the ``\S+`` operator which is "anything but space" will probably match more then it should:

https://github.com/ossec/ossec-hids/blob/b7cfd4db56b15632a33c204f9dd494a43e82f664/etc/decoder.xml#L3093-L3104

**Comment by ddpbsd** [comment]
@iasdeoupxe Is there a specific instance of `\S` you're referring to?

**Comment by iasdeoupxe** [comment]
I basically mean the following changed in this PR:

```
<regex offset="after_prematch">^'(\w+)' , wrong password, IP:(\S+)</regex>
```

in the log snippet posted above i can see e.g.:

```
wrong password, IP:127.0.0.1","level"
```

IIUC the ``\S+`` means "everything but space" where not only the IP but also the following text will be extracted into the IP or am i wrong?

**Comment by aquerubin** [comment]
Yikes!  You’re right.  Will fix.

Tony

**Comment by iasdeoupxe** [comment]
Initial fix in https://github.com/ossec/ossec-hids/pull/1724, did a minor update in https://github.com/ossec/ossec-hids/pull/1725

**Pull request merged**
