### PR TITLE
Wait between active response flushes during shutdown to prevent the processes from entering sleep state right away.

### PR DESCRIPTION
**Pull request by aquerubin**
This further addresses issue #609 by preventing the processes from starting up simultaneously and running concurrently in the first place. While the previous patch addressed system load between processes that were already running simultaneously, this fix avoids that altogether.

### CODE REVIEW

**Comment by jrossi** [comment]
Sorry about being so slow with updates.   I have often thought about doing this but was worried the response time and queue would back under load.  I worry that this little change would have a huge effect on some people like @atomicturtle.  Is this a real issue? @ossec crew any input? 


I had started something around batching and stuff a while ago but needed more eyes and love and time. https://github.com/jrossi/ossec-hids/tree/ossec-execd-lua-scripts-state?files=1

**Comment by awiddersheim** [comment]
I'm also worried. Would be nice if someone with a good amount of throughput could test.

**Comment by aquerubin** [comment]
On Fri, 3 Jul 2015, Andrew Widdersheim wrote:

> I'm also worried. Would be nice if someone with a good amount of 
> throughput could test.

Amount of processing throughput is not the real question.  The desired end 
state is that all AR records are flushed from the system as quickly and 
painlessly as possible during OSSEC shutdown.  The question is really how 
effectively to use that processing throughput to achieve that desired 
state.  Is it better to instantly startup a whole bunch of processes that 
are almost certain to go into lock/sleep states of varying duration and 
walk away (letting the system sort things out), or, simply run the 
processes sequentially as fast as each flush can be completed (completely 
avoiding lock/sleep cycles altogether).  Empirical testing when the number 
of AR entries number in the hundreds shows the former is a really bad 
idea.  But don't take my word for it, do your own rigorous load testing 
during shutdown and verify for yourself what the effects in either case.

Remember this patch just adds a wait() only during OSSEC shutdown.  It's a 
bit ironic that if you had a situation where a server is undergoing a 
persistent attack that creates lots of AR entries, certain actions that 
might be taken to quiesce the server and shutdown OSSEC as part of that 
action actually may make the situation worse by causing a self-induced 
DoS.


Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com

**Comment by jrossi** [comment]
@aquerubin you are correct and I was and am completely WRONG :) let me start again ;)

**Comment by awiddersheim** [comment]
Yeah I totally misunderstood this as well.

**Pull request merged**
