### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
fwiw, this is a subset of wazuh/wazuh#171

### CODE REVIEW

**Comment by ddpbsd** [comment]
I don't like changing `groupping` at the moment, for backwards compatibility reasons. Everything else I saw looked good though

**Comment by jsoref** [comment]
Dropped

**Comment by atomicturtle** [comment]
Ha, this is fantastic. I wonder how many of those were my fault :P

**Comment by jsoref** [comment]
fwiw, this is more or less about average for spelling errors in a project. (I haven't actually generated a metric for this, but someone could easily build one by reviewing the PRs I've made against dozens of projects...)

**Comment by ddpbsd** [comment]
Thanks for going through all of those!

**Pull request merged**
