### PR TITLE
Fix README display IP as string

### PR DESCRIPTION
**Pull request by hugoboos**

### CODE REVIEW

**Comment by aquerubin** [comment]
Aren't these stored as strings in the DB now?

Tony

**Comment by ddpbsd** [comment]
From the mysql.schema:
```
    src_ip          VARCHAR(46),
    dst_ip          VARCHAR(46),
```

**Comment by aquerubin** [comment]
Right.  So inet_ntoa in the select example isn't required any more is it?

Tony

**Comment by hugoboos** [comment]
I've changed the column types to `VARCHAR(46)` but still a number is stored for the IP address.

**Comment by aquerubin** [comment]
Were the numbers stored in the DB before the upgrade to 2.9?  If they were already in the DB then you’ll need to convert the existing data and schema using the script in src/os_dbd/convert-dbd-ipv6.sql.  Instructions are embedded in the script.  If you already converted the DB schema but the addresses are still being stored as numbers then we’ve got a separate problem.

**Pull request merged**
