### PR TITLE
Check for a NULL from malloc.

### PR DESCRIPTION
**Pull request by ddpbsd**
I'm not sure if returning 0 is the best option here, just copied it from issue #752

### CODE REVIEW

**Comment by ddpbsd** [comment]
I think I got the return right in c63b476, but I'm not totally positive.

**Comment by dcid** [comment]
I always like to add some logging on memory failures, but tricky to do on some cases. Seems ok here.

It might be better long term to have a saved buffer we can release on memory failure error, just so we can log things properly before exiting. Unrelated to this :)

**Comment by ddpbsd** [comment]
I can add some merrors to the failures, that shouldn't be too hard.

**Comment by ddpbsd** [comment]
I added some merrors, although I didn't do anything to help specify which one was erroring out. Not sure if it matters at that point?

**Pull request merged**
